#! /usr/bin/env python

'''
Query InfluxDB
'''

import sys
import argparse
import time
import itertools
import yaml
import requests

def main():
    parser = argparse.ArgumentParser(
        description="Query InfluxDB.",
        epilog='''Start queries with SELECT, DELETE, SHOW, CREATE, DROP, GRANT,
            REVOKE, ALTER, SET, KILL''',
    )
    parser.add_argument('config', help="config file")
    parser.add_argument('query', nargs='+', help="InfluxDB query")
    parser.add_argument(
        '-a', '--nolimit',
        help="print all results",
        action='store_true',
    )
    args = parser.parse_args()

    with open(args.config) as fhl:
        cfg = yaml.load(fhl)

    limit = None if args.nolimit else cfg['limit']

    query = ' '.join(args.query)
    print query
    try:
        start = time.time()
        req = requests.get(
            cfg['url'],
            auth=(cfg['user'], cfg['password']),
            params={
                'db': cfg['db'],
                'q': query,
                'pretty': 'true',
            },
        )

        if args.nolimit:
            print req.text
        else:
            i = 0
            text = ''
            for line in req:
                text += line
                i += line.count('\n')
                if i > limit:
                    break
            print text

        print "Queried in %fs" % (time.time() - start)
    except KeyboardInterrupt:
        pass

if __name__ == '__main__':
    sys.exit(main())
