#! /usr/bin/env python

import sys
import argparse
import pprint
import yaml
import requests

def main():
    parser = argparse.ArgumentParser(
        epilog='''Start queries with SELECT, DELETE, SHOW, CREATE, DROP, GRANT,
            REVOKE, ALTER, SET, KILL''',
    )
    parser.add_argument('config', help="config file")
    parser.add_argument('query', nargs='+', help="InfluxDB query")
    parser.add_argument(
        '-v', '--verbose',
        help="print whole result data structure regardless",
        action='store_true',
    )
    parser.add_argument(
        '-a', '--nolimit',
        help="print all results",
        action='store_true',
    )
    args = parser.parse_args()

    with open(args.config) as fhl:
        cfg = yaml.load(fhl)

    limit = None if args.nolimit else cfg['limit']

    req = requests.get(
        cfg['host'],
        auth=(cfg['user'], cfg['password']),
        params={
            'db': cfg['db'],
            'q': ' '.join(args.query),
        },
    )

    res = req.json()
    if not args.verbose and \
        res.keys() == ['results'] and \
        len(res['results']) == 1 and \
        res['results'][0].viewkeys() == set(('series',)) and \
        len(res['results'][0]['series']) == 1 and \
        res['results'][0]['series'][0].viewkeys() == \
            set(('columns', 'name', 'values')):

        # If there's only results and series
        pprint.pprint(res['results'][0]['series'][0]['values'][:limit])
    else:
        pprint.pprint(res)

if __name__ == '__main__':
    sys.exit(main())
